---
title: "openFDA medicinal product coocc"
output: html_notebook
---

This function calls the adverse events endpoint of the openFDA API to retrieve reports submitted between 01-01-2016 and 01-06-20117. There is a limit of 100 reports you can retrieve per query. 
```{r}

get_data <- function(k){
  
  api_url <- "https://api.fda.gov/drug/event.json?search=receivedate:[20160101+TO+20170601]&limit=100"
  data <- jsonlite::fromJSON(api_url, simplifyDataFrame = T)
  data <- data$results
  data <- data$patient
  data <- data$drug

  data <- sapply(data,function(x) x$medicinalproduct)
  all_data <- data
  
  for(i in 1:k){
    api_url <- paste("https://api.fda.gov/drug/event.json?search=receivedate:[20160101+TO+20170601]&limit=100&skip=", i*100, sep = "")
    data <- jsonlite::fromJSON(api_url, simplifyDataFrame = T)
    data <- data$results
    data <- data$patient
    data <- data$drug

    data <- sapply(data,function(x) x$medicinalproduct)
    all_data <- c(all_data,data)
  }
  return(all_data)
}

```


Get the 2000 reports and clean the data (drug names)
```{r}

all_reports <- get_data(99)
all_reports <- sapply(all_reports, function(x) gsub("\\.","",x))
all_reports <- sapply(all_reports, function(x) gsub("\\{","",x))



meds_list <- as(all_reports, "transactions")

summary((meds_list))
summary(itemFrequency(meds_list))

frequentMeds <- apriori(meds_list, parameter=list(target="frequent", supp = 0.01))
itemFrequencyPlot(meds_list, topN = 5, type="absolute")

rules <- apriori(meds_list,parameter = list(supp=0.002, conf = 0.01, maxlen = 10, minlen = 2))
#, appearance = list (default="rhs",lhs="RETROVIR")
rules <- rules[!is.redundant(rules, measure = "lift")]
inspect(rules[!is.redundant(rules, measure = "lift")])

sorted_rules <- sort(rules, by = "lift", decreasing = T)

inspect(head(sorted_rules, n=50))

```

Visualisations
```{r}
source("http://bioconductor.org/biocLite.R")
    biocLite("Rgraphviz")

rules_to_plot <- head(sorted_rules,15)
plot(rules_to_plot, method = "graph", control = list(type = "items",engine = "graphviz") )


```

